import "reflect-metadata"
import { Fields } from "remult"
import { iField } from "../decorators/iField"

/**
 * BaseObject — abstract base class for all iRAF business entities.
 *
 * Provides:
 * - `id`: cuid primary key generated by Remult
 * - `createdAt` / `updatedAt`: filled by @iEntity saving hook
 * - `createdBy` / `updatedBy`: filled by @iEntity saving hook (remult.user.name)
 *
 * Example:
 * ```ts
 * @iEntity("customers", { caption: "Customer", icon: "Users" })
 * export class Customer extends BaseObject {
 *   @iField.string({ caption: "Name", required: true })
 *   name = ""
 * }
 * ```
 */
export abstract class BaseObject {
  @Fields.cuid()
  id = ""

  @iField.date({ caption: "Created At", readOnly: true, hidden: true, auditField: true })
  createdAt?: Date

  @iField.date({ caption: "Updated At", readOnly: true, hidden: true, auditField: true })
  updatedAt?: Date

  @iField.string({ caption: "Created By", readOnly: true, hidden: true, auditField: true })
  createdBy = ""

  @iField.string({ caption: "Updated By", readOnly: true, hidden: true, auditField: true })
  updatedBy = ""
}
